version: '3'

services:
  api:
    build: .
    container_name: finance-manager-api
    volumes:
      - ~/private:/app/private
    ports:
      - "4001:80"
    env_file:
        - ~/.env
    depends_on:
        - db

  db:
    image: postgres:15
    container_name: postgres-db
    volumes:
      - ~/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ~/postgres.env
